### ISSUE TITLE
Users unable to change php

### ISSUE THREAD

**Issue by SjamonDaal** [Skamasle/sk-php-selector#1]
Hi,

How am I able to five the user access to change the PHP Version?

By default there is no setting if you are logged on as the user but when I change the /usr/local/vesta/web/templates/user/edit_web.html and add the following code it won't work.

Please advice.

`<tr>
                                <td class="vst-text input-label">
                                    <?php print __('Web Template')  . "<span class='optional'>" .strtoupper($_SESSION['WEB_SYSTEM']) . "</span>";?>
                                </td>
                            </tr>
							<tr>
                                <td>
                                    <select class="vst-list" name="v_template">
                                        <?php
                                            foreach ($templates as $key => $value) {
                                                echo "\t\t\t\t<option value=\"".htmlentities($value)."\"";
                                                $svalue = "'".$value."'";
                                                if ((!empty($v_template)) && ( $value == $v_template ) || ($svalue == $v_template)){
                                                    echo ' selected' ;
                                                }
                                                echo ">".htmlentities($value)."</option>\n";
                                            }
                                        ?>
                                    </select>
                                </td>
                            </tr>
							<?php if (!empty($_SESSION['WEB_BACKEND'])) { echo ""; ?>
							<tr>
                                <td class="vst-text input-label">
                                    <?php print __('Backend Template') . " <span class='optional'>" . strtoupper($_SESSION['WEB_BACKEND']) . "</span>";?>
                                </td>
                            </tr>
							<tr>
                                <td>
                                    <select class="vst-list" name="v_backend_template">
                                        <?php
                                            foreach ($backend_templates as $key => $value) {
                                                echo "\t\t\t\t<option value=\"".$value."\"";
                                                $svalue = "'".$value."'";
                                                if ((!empty($v_backend_template)) && ( $value == $v_backend_template ) || ($svalue == $v_backend_template)){
                                                    echo ' selected' ;
                                                }
                                                if ((empty($v_backend_template)) && ($value == 'default')){
                                                    echo ' selected' ;
                                                }
                                                echo ">".htmlentities($value)."</option>\n";
                                            }
                                        ?>
                                    </select>
                                </td>
                            </tr>
							<?php echo ""; }?>	`

**Comment by Skamasle** [comment]
Yes, this is correct, but is a vesta issue, httpd is not available in users tab, proxy template too, there are discutions about this in bug tracker

I cant help you with this.

**Comment by SjamonDaal** [comment]
Thanks for the reply.

So there is no known solution to fix this?

**Comment by Skamasle** [comment]
There is no option in vesta to enable it, maybe developers get some fix in new version next year.
