### ISSUE TITLE
CENTOS 6.9 VESTACP VERSION  0.9.8-19 syntax error near unexpected token

### ISSUE THREAD

**Issue by BartManX** [Skamasle/sk-php-selector#2]
----------------------- CENTOS 6.9 VESTACP VERSION  0.9.8-19 FRESH INSTALL ----------------------- 

[root@server2 /]# wget https://raw.githubusercontent.com/Skamasle/sk-php-selector/master/sk-php-selector2.sh
--2018-02-21 14:59:19--  https://raw.githubusercontent.com/Skamasle/sk-php-selector/master/sk-php-selector2.sh
Resolving raw.githubusercontent.com... 151.101.8.133
Connecting to raw.githubusercontent.com|151.101.8.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5180 (5.1K) [text/plain]
Saving to: “sk-php-selector2.sh”

100%[======================================>] 5,180       --.-K/s   in 0s

2018-02-21 14:59:20 (114 MB/s) - “sk-php-selector2.sh” saved [5180/5180]

[root@server2 /]# bash sk-php-selector2.sh
sk-php-selector2.sh: line 84: syntax error near unexpected token `}'
sk-php-selector2.sh: line 84: `}'

**Comment by Skamasle** [comment]
This concrete fail is not test well, I fix that issue.

**Comment by BartManX** [comment]
resolved by changing line 84
`fixit 72
}
`
to 

`fixit 72
fi
}
`

**Comment by Skamasle** [comment]
Yes, I commit it 10 minutes a go.

Thanks
