### ISSUE TITLE
Able to change the versions but phymyadmin issue

### ISSUE THREAD

**Issue by nisnym** [Skamasle/sk-php-selector#28]
I can change the versions of PHP by using the vesta cp web option but it usually fails to restart the httpd even then resubmitting and manually enabling it changes the PHP version. But the problem occurs with phpMyAdmin. It usually gives the error of 
`404 Not Found
The requested URL /phpmyadmin was not found on this server.`
I tried various solutions found on vesta cp forum but non of them is working. 
Link of threads which I referred:
1. [https://forum.vestacp.com/viewtopic.php?f=10&t=19134&sid=60a0b4c2f18ebb467fd0640ec369cd8c&start=20](url)

**Comment by Skamasle** [comment]
What OS you are using ?
What is your default php version ?

If you get 404 when access to phpmyadmin, maybe this isnt installed inserver

**Comment by nisnym** [comment]
I'm using CENTOS  7.
And one more problem is that sometimes it is just not possible to restart the httpd because of the version change. 
That error was because it was using phpMyAdmin 5.0.2 which only supports PHP 7. 1 above so downgrading to phpMyAdmin 4.9.5 helped me.

**Comment by juanremi** [comment]
> I'm using CENTOS 7.
> And one more problem is that sometimes it is just not possible to restart the httpd because of the version change.
> That error was because it was using phpMyAdmin 5.0.2 which only supports PHP 7. 1 above so downgrading to phpMyAdmin 4.9.5 helped me.

https://github.com/Skamasle/sk-php-selector/issues/21#issuecomment-587209893

**Comment by nisnym** [comment]
I believe the above solution will work for everyone else to and closing the issue.
