### ISSUE TITLE
mirror.skamasle.com

### ISSUE THREAD

**Issue by Barmunksu** [Skamasle/sk-php-selector#29]
why do you use an external source to download the script? It does not look safe.

from: curl -s http://mirror.skamasle.com/vestacp/PHP/sk-php${1}-centos.sh
to: curl -s https://raw.githubusercontent.com/Skamasle/sk-php-selector/master/sk-php${1}-centos.sh

**Comment by Skamasle** [comment]
Hi, sorry for delay I change location, forget it, i upload .sh files 7 months a go, so now it was downloaded from github
