### ISSUE TITLE
chmod: cannot access ‘/opt/remi/php70/root/var/lib/php/session’: No such file or directory

### ISSUE THREAD

**Issue by BartManX** [Skamasle/sk-php-selector#3]
----------------------- CENTOS 7 VESTACP VERSION  0.9.8-19 FRESH INSTALL ----------------------- 

You have remi repo installed and run:
CentOS Linux release 7.4.1708 (Core)
##########
Start installing aditional php version
##########
Actually you runing php 5.6, so I will skip it
Instaling PHP 5.4
........
PHP  Ready!
Instaling PHP 5.5
.......
PHP  Ready!
Skip php 5.6 actually installed
Installing PHP 7.0
.......
chmod: cannot access ‘/opt/remi/php70/root/var/lib/php/session’: No such file or directory
PHP  Ready!
Installing PHP 7.1
.......
chmod: cannot access ‘/opt/remi/php71/root/var/lib/php/session’: No such file or directory
PHP  Ready!
Installing PHP 7.2
.......
chmod: cannot access ‘/opt/remi/php72/root/var/lib/php/session’: No such file or directory
PHP  Ready!

**Comment by Skamasle** [comment]
Yes, this try fix old paths, new PHP7 in remi remo put files inside /etc/

I will check it
