### ISSUE TITLE
Php 8.0 

### ISSUE THREAD

**Issue by maijye** [Skamasle/sk-php-selector#31]
Thank you for script! 🙏
It’s very nice, I have used it for a few years.
But now when I start it, I get this error message:
```
Cant get actual php versión
Run php -v and ask on forum or yo@skamasle.com
Leaving instalation...
```
php -v
8.0.0

I think this script doesn’t know new 8 version PHP.
Could you update it?
Thanks!

**Comment by SwapnilAkolkar** [comment]
same issue, I try quick fix by changing the code in sh file , but I lost php 8 in drop down . it installed all old php versions but still my PHP CLI is php 8 which causing me problem while instaling through composer & while serving application as 2 diffrent php versions one for cli and other for serving i.e. one which shown in phpinfo()
